apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-su
spec:
  replicas: 1
  selector:
    sb-instanceid-storm: ui
  template:
    metadata:
      labels:
        sb-instanceid-storm: ui
        service-broker: sb-instanceid-storm
    spec:
      containers:
      - name: zookeeper
        image: 172.30.188.59:5000/service-broker/docker-storm-cluster
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "ui"
        - name: ZK_SERVER_1_SERVICE_HOST
          value: "sb-instanceid-zk"
        - name: APACHE_STORM_NIMBUS_SERVICE_HOST
          value: sb-instanceid-sn
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}

