apiVersion: v1
kind: Service
metadata:
  name: sb-instanceid-sd
spec:
  selector:
    sb-instanceid-storm: drpc
  ports:
  - protocol: TCP
    port: 3772
  externalIPs:
  - 10.1.130.155
  #type: NodePort
