apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-su
spec:
  replicas: 1
  selector:
    sb-instanceid-storm: ui
  template:
    metadata:
      labels:
        sb-instanceid-storm: ui
        service-broker: sb-instanceid-storm
    spec:
      containers:
      - name: zookeeper
        image: registry.dataos.io/jared/storm_test:latest
        ports:
           - containerPort: 8080
        env:
        - name: CONFIGURE_ZOOKEEPER
          value: "true"
        - name: STORM_CMD
          value: "ui"
        - name: ZK_SERVER_1_SERVICE_HOST
          value: "10.1.236.92"
        - name: ZK_SERVER_2_SERVICE_HOST
          value: "10.1.236.93"
        - name: ZK_SERVER_3_SERVICE_HOST
          value: "10.1.241.54"
        - name: APACHE_STORM_NIMBUS_SERVICE_HOST
          value:  sb-instanceid-sn
        volumeMounts:
        - name: storm-data
          mountPath: /opt/apache-storm/storm-local
      volumes:
      - name: storm-data
        emptyDir: {}

