apiVersion: v1
kind: Service
metadata:
  name: sb-instanceid-su
spec:
  selector:
    sb-instanceid-storm: ui
  ports:
  - protocol: TCP
    port: 8080
  externalIPs:
  - 10.1.130.155
  #type: NodePort
